#!/bin/bash
# Set fds as an executable command on unix systems
# Script partially generated by GPT

chmod +x fds.py
cp fds.py fds
mkdir -p ~/.local/bin
mv fds ~/.local/bin/

# Check if ~/.local/bin is already in PATH
if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
    echo "Adding $HOME/.local/bin to PATH"
    
    # Append to the appropriate shell configuration file
    if [ -n "$ZSH_VERSION" ]; then
        # For Zsh
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
        source ~/.zshrc
    elif [ -n "$BASH_VERSION" ]; then
        # For Bash
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
    else
        echo "Unknown shell. Please add $HOME/.local/bin to PATH manually."
    fi
else
    echo "$HOME/.local/bin is already in PATH"
fi